### ISSUE TITLE
Endpoint: GET monthly_affirmations

### ISSUE THREAD

**Issue by amypetrie** [tmaria17/mood_board_be#28]

**Comment by amypetrie** [comment]
Endpoint: GET /api/v1/users/:id/affirmations?date=YYYY-MM

(i.e. GET /api/v1/users/:id/calendar_day?date=2019-02)

This endpoint is called when the User clicks "Affirmations" on the Calendar page and is redirected to the Affirmations page to see all affirmations written that month.

JSON Response:

{:data=>
{:id=>nil,
:type=>"affirmation_wrapper",
:attributes=>
{:date=>"2019-02",
:affirmations=>[
{:affirmation_text=>"I am beautiful! 2"},
{:affirmation_text=>"I am beautiful! 4"}
]
}
}
}

**Comment by tmaria17** [comment]
{:data=>
  {:id=>nil,
   :type=>"affirmation_wrapper",
   :attributes=>
    {:date=>"2019-02",
     :affirmations=>
      [{:affirmation_text=>"I am beautiful! 2"},
       {:affirmation_text=>"I am beautiful! 4"}]}}}

This is what the response looks like!
